version: '3.9'
services:
  mosquitto-broker:
    image: eclipse-mosquitto:2
    container_name: mosquitto-broker
    ports:
      - "1883:1883"
      - "8883:8883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
  postgres:
    image: postgres:14.4
    container_name: postgres
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - /var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: iot-project
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 10
  mongo:
    image: "mongodb-kafka-base-mongod:1.0"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
  car1:
    image: amazoncorretto:17-alpine-jdk
    volumes:
      - ./Machine-Simulator-1.0.jar:/app/Machine-Simulator-1.0.jar
    command: java -jar /app/Machine-Simulator-1.0.jar
    environment:
      - CAR_NUMBER=С843АС161
      - BROKER_IP=mosquitto-broker
    depends_on:
      - mosquitto-broker
  car2:
    image: amazoncorretto:17-alpine-jdk
    volumes:
      - ./Machine-Simulator-1.0.jar:/app/Machine-Simulator-1.0.jar
    command: java -jar /app/Machine-Simulator-1.0.jar
    environment:
      - CAR_NUMBER=Ф777АС198
      - BROKER_IP=mosquitto-broker
    depends_on:
      - mosquitto-broker
  car3:
    image: amazoncorretto:17-alpine-jdk
    volumes:
      - ./Machine-Simulator-1.0.jar:/app/Machine-Simulator-1.0.jar
    command: java -jar /app/Machine-Simulator-1.0.jar
    environment:
      - CAR_NUMBER=Е666КХ161
      - BROKER_IP=mosquitto-broker
    depends_on:
      - mosquitto-broker
  car4:
    image: amazoncorretto:17-alpine-jdk
    volumes:
      - ./Machine-Simulator-1.0.jar:/app/Machine-Simulator-1.0.jar
    command: java -jar /app/Machine-Simulator-1.0.jar
    environment:
      - CAR_NUMBER=А432МР750
      - BROKER_IP=mosquitto-broker
    depends_on:
      - mosquitto-broker            
